# Generated by Django 3.2.18 on 2023-05-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='api_wellnumber',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='brine',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='gas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='oil',
            field=models.TextField(),
        ),
    ]
